[project]
name = "django-saintrelion-libs"
version = "2.1.3"
description = "Modular Django libraries"
dependencies = [
    "django",
    "djangorestframework",
    "djangorestframework-simplejwt",
    "django-cors-headers",
    "webauthn",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"