[project]
name = "django-saintrelion-libs"
version = "1.0.1"
description = "Modular Django libraries"
dependencies = [
    "django",
    "djangorestframework",
    "webauthn"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"